### ISSUE TITLE
"520 Origin Error"

### ISSUE THREAD

**Issue by Ortovoxx** [steamcmd/api#12]
Only got a few times and is working now. I assume this is a problem with the host due to `cloudflare-nginx` mention rather than the software? Just thought I would let you know.

**Comment by jonakoudijs** [comment]
Thanks for opening the issue! That error means that something went wrong with the backend (hosted on Heroku). The hosting is quite stable but sometimes it times out when 'steamcmd' has an update which causes the request to take longer then 30s.

This is a known issue sadly and I'm hoping to solve this by catching it if 'steamcmd' is updating and returning a corresponding response.

**Comment by Ortovoxx** [comment]
Ah okay I figured something as much. Just thought I would let you know! Excited to see how it progresses :)

**Comment by jonakoudijs** [comment]
Awesome and please continue to do so :) having issues and feature requests known will help towards improving the service!
