### ISSUE TITLE
UpToDateCheck

### ISSUE THREAD

**Issue by silent001** [steamcmd/api#13]
I would like to request if possible a uptodatecheck much like the steamapi is supposed to give however some games do not have it implemented so I was wondering if you could do it. I have looked at your api and can get latest build ID with jq and filtering with ```.data.${appid}.depots.branches.public.buildid``` I am sure this should be easy to implement if this feature is not already available(did not find anything on your docs about this).
The steamapi takes appid and buildid to compare

**Comment by jonakoudijs** [comment]
Can you elaborate a bit more on your use case? The API (on the `/info` endpoint) executes `steamcmd` and parses the output and without change outputs it in JSON. Do you suggest to add extra information to this output outside of what the `steamcmd` command provides?

Comparing data and information should generally be done on the API client/consumer side. If you can provide an use case and some more information I can probably help you a bit better.
