### ISSUE TITLE
A lot of games aren't found

### ISSUE THREAD

**Issue by askebv** [steamcmd/api#27]
I don't have time to look into why and come with more helpful information but several games return a 404:
https://api.steamcmd.net/v1/info/1455840
https://api.steamcmd.net/v1/info/577970
https://api.steamcmd.net/v1/info/346900

Just to name a few.

**Comment by jonakoudijs** [comment]
This is a known issue with Windows (only) game (servers). This is being worked on in issue: https://github.com/steamcmd/api/issues/16. If you want to keep track of the progress, I suggest to subscribe to that issue.

**Comment by jonakoudijs** [comment]
This has been fixed by the amazing @1337cookie and the fix added to version v1.9.0 has been deployed to the live API as well. The ID's you mentioned are now working on api.steamcmd.net.
