### ISSUE TITLE
Request: Build and Deploy Images to Docker Hub

### ISSUE THREAD

**Issue by EthanC** [steamcmd/api#36]
Deploying images to Docker Hub would allow those of us who self-host (for stability) to specify `steamcmd/api:latest` (for example) rather than manually building the image. The benefits of this are easier initial deployment and updates.

It's possible to automate this task using [GitHub Actions](https://docs.docker.com/build/ci/github-actions/).

**Comment by jonakoudijs** [comment]
Ah I see this is not documented in the README but this is already the case. The live API uses the Docker image from the Hub: https://hub.docker.com/r/steamcmd/api. And this is done via Github Actions as well with every new tag created in the repo (thus version).

The default settings should be sufficient for most. The port the API listens on can be changed by setting the `PORT` environment variable, the default is **8080**. And if you would want to enable caching (only Redis is supported atm) then you can configure with environment variables as well, for example:
          REDIS_SSL: "True"
          REDIS_PORT: "25061"
          REDIS_HOST: "steamcmd-redis-do-user-3747236-0.b.db.ondigitalocean.com"
          REDIS_USERNAME: "default"
          REDIS_PASSWORD: "AVNS_hR0j3_KVlIdV3AITvGU"

Seeing I am currently building the API I have not extended the README with examples yet, hopefully I will be able to finish up soon.

**Comment by EthanC** [comment]
Nice, that's what I was looking for. Thanks!
