### ISSUE TITLE
Allow Redis URL for hosts that provide a Redis connection string

### ISSUE THREAD

**Issue by sxalexander** [steamcmd/api#42]
For many cloud platforms ([heroku](https://devcenter.heroku.com/articles/heroku-redis), [render](https://render.com/docs/connecting-to-redis-with-ioredis), [railway](https://docs.railway.app/databases/redis), [fly.io](https://fly.io/docs/reference/redis/)) Redis connection info is provided via a connection string (ie. a `REDIS_URL` environment var)

It would be great to allow the use of `REDIS_URL` as an option along side the setting seperate env variables to make it easier to run on those platforms.

**Comment by jonakoudijs** [comment]
This looks like a non-breaking improvement! Thank you for taking the time to make the PR as well.

Let me test it this weekend to make sure nothing will break and I can merge it :)

**Comment by jonakoudijs** [comment]
The change has been merged and deployed in v1.13.0. The deployment to Fly.io however fails, I will have a look at that later. Can you verify that this change solves your problem on your end?

Thanks again for your contribution :)

**Comment by jonakoudijs** [comment]
Just tested this on Fly.io and apparently the failed deployment from yesterday was an issue at the Fly.io side. The deployment now works fine as expected.

**Comment by sxalexander** [comment]
Glad to hear it, thanks for merging 👍🏾 I've got this running on Render now with no issues as well
