### ISSUE TITLE
Missing data for CrossFire Legion (1072190)

### ISSUE THREAD

**Issue by Masquerade64** [steamcmd/api#49]
Hello,
I tried to retrieve data for CrossFire Legion (AppID 1072190) from api.steamcmd.net, but the "depots" information is missing. Could this be due to "_missing_token" being true? I am trying to get the ID of the latest Build of the game (12943512 at time of writing) as well of the time this build was released.

Please may you let me know if this is something that could be fixed.
Thanks!

**Comment by jonakoudijs** [comment]
Yes, that seems to be case indeed. The API uses the [steam](https://steam.readthedocs.io/en/stable/api/steam.client.builtins.html) Python module under the hood. The module's docs describe the following:

> Access token is needed to access full information for certain apps, and also package info. Each app and package has its’ own access token. If a token is required then _missing_token=True in the response.
> 
> App access tokens are obtained by calling [get_access_tokens()](https://steam.readthedocs.io/en/stable/api/steam.client.builtins.html#steam.client.builtins.apps.Apps.get_access_tokens), and are returned only when the account has a license for the specified app.

So sadly it seems that you can only retrieve the information with an account that owns the game. The API currently does not support using your Steam account. Do you host the API yourself or use the public api.steamcmd.net service? Maybe it can be relatively easily incorporated but then you would likely have to host it yourself (seeing I don't have the game in my Steam account).

**Comment by Masquerade64** [comment]
Thank you for your information!
